export default {
  user: {
    NOT_FOUND: 'User account not found',
    ALREADY_EXIST: 'User account already exist',
    LOGIN_SUCCESS: 'User login successful',
    LOGIN_FAIL: 'User login failed',
    PASSWORD_NOT_MATCH: 'Password is not matched',
    CREATENTIAL_REQUIRED: 'User credential required',
    CREATE_SUCCESS: 'Account created successfully',
    CREATE_ERROR: 'Error with create user account',
    UPDATE_SUCCESS: 'User account update successfully',
    UPDATE_ERROR: 'Error with update user account',
    DELETE_SUCCESS: 'User account delete successfully',
    DELETE_ERROR: 'Error with delete user account',
  },
  doctor: {
    NOT_FOUND: 'Doctor details not found',
    SEARCH_SUCCESS: 'Search doctors successfull',
    SEARCH_ERROR: 'Error with search doctors',
    CREATE_SUCCESS: 'Doctor added successfully',
    CREATE_ERROR: 'Error with adding doctor',
    UPDATE_SUCCESS: 'Doctor details update successfully',
    UPDATE_ERROR: 'Error with update Doctor details',
    DELETE_SUCCESS: 'Doctor details delete successfully',
    DELETE_ERROR: 'Error with delete Doctor details',
  },
};
